name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Run Prettier
        run: npm run prettier:fix

      - name: Build Project
        run: npm run build --if-present

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          REDIS_SECRET_PASS: ${{ secrets.REDIS_SECRET_PASS }}
        run: npm test
